using GodotNodeGenerator.Tests.TestHelpers;

namespace GodotNodeGenerator.Tests
{
    /// <summary>
    /// Tests that verify generated code against expected output snapshots
    /// </summary>
    public class OutputSnapshotTests : NodeGeneratorTestBase
    {
        [Fact]
        public void Keeps_Comments_In_Generated_Code()
        {
            // Arrange: Create minimal source
            var sourceCode = CreateSourceTemplate("CommentTest", scenePath: "CommentScene.tscn");

            // Create a simple scene with just one node
            var scenePath = "CommentScene.tscn";
            var sceneContent = @"
[gd_scene format=3]

[node name=""Node"" type=""Node""]
";

            // Act: Run the generator
            var outputs = RunSourceGenerator(sourceCode, [(scenePath, sceneContent)]);
            var generatedFile = outputs.FirstOrDefault(f => f.HintName == "CommentTest.g.cs");
            var generatedCode = generatedFile.SourceText.ToString();

            // Assert: Verify all expected comments are present
            Assert.Contains("// <auto-generated/>", generatedCode);
            Assert.Contains("// Generated node accessors for CommentTest", generatedCode);
            Assert.Contains("#region Node Tree Accessors", generatedCode);
            Assert.Contains("#endregion", generatedCode);
        }
    }
}
